stages:
  - sanity

sanity_merge_request:
  stage: sanity
  tags:
    - asa2-miia
  script:
    - echo "Sanity check (Merge Request)"
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

sanity_main:
  stage: sanity
  tags:
    - asa2-miia
  script:
    - echo "Sanity check (main)"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
